### ISSUE TITLE
Lein Cucumber 0.2.0 always throws ClassNotFoundException: cucumber.formatter.FormatterFactory

### ISSUE THREAD

**Issue by awostenberg** [nilswloka/lein-cucumber#13]
The readme.md instructions fork fine for   :dev-dependencies [[lein-cucumber "0.1.0"]].

However following them with  :dev-dependencies [[lein-cucumber "0.2.0"]] always throws the error below:

Steps.
1. lein new
2. revise project.clj:
(defproject cuke "1.0.0-SNAPSHOT"
  :description "leiningen cucumber tutorial"
  :dependencies [[org.clojure/clojure "1.3.0"]]
  :dev-dependencies [[lein-cucumber "0.2.0"]])
3. lein deps
4. lein cucumber
     error:    Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: cucumber.formatter.FormatterFactory

**Comment by undees** [comment]
I can replicate this issue on my machine (OS X 10.7).

**Comment by nilswloka** [comment]
I will have a look at the issue as soon as possible. I suspect a version mismatch with cucumber-jvm. In the meantime, you might want to have a look at the 1.0 branch.

**Comment by nilswloka** [comment]
This has indeed been an issue caused by incompatible transitive dependencies of the cucumber-clojure version. I suggest going for version 1.0.0, which I just released to clojars.

**Comment by awostenberg** [comment]
Thanks.

On Sat, Apr 28, 2012 at 5:19 PM, Nils Wloka <
reply@reply.github.com

**Comment by undees** [comment]
Switching to `:plugins [[lein-cucumber "1.0.0"]]` fixed the issue for me as well; thank you!
