### ISSUE TITLE
Allow multiple reports to be specified

### ISSUE THREAD

**Issue by yatesco** [nilswloka/lein-cucumber#23]
My use case is that I want to execute 'lein cucumber' and have a progress report in the console as well as a junit report in the target directory (to be picked up by jenkins for example).

I can execute 'lein cucumber --format pretty' _or_ 'lein cucumber --format junit:target/cucumber-test-report.xml' but how can I combine them?  

The following straws didn't work when I clutched at them:  'lein cucumber --format pretty,junit:target/cucumber-report.xml', 'lein cucumber --format pretty --format junit:target/cucumber-report.xml'

Any and all help is appreciated!

**Comment by nilswloka** [comment]
In theory, the last one (multiple -f options) should work, as the plugin simple instantiates RuntimeOptions with the arguments given to leiningen. Could you try that one again and see what happens?
- Does it generate a junit report in target/cucumber-report.xml? 
- Does it generate a cucumber.out in target/test-reports?
- What does the console output look like?

I'll try and have a look at the issue this weekend.

**Comment by yatesco** [comment]
Hi Nils,

(apologies for the delay) - you are right: 'lein -f
junit:/target/myfile.xml -f pretty' produces both target/myfiles.xml and
the report to the console.

Thanks a bunch.

**Comment by nilswloka** [comment]
You're welcome! I'll close this issue for now.
