### ISSUE TITLE
More configuration options

### ISSUE THREAD

**Issue by nilswloka** [nilswloka/lein-cucumber#5]
Add configuration options (analogous to `:cucumber-feature-path`):
- `:cucumber-output-dir` for configuring the output directory
- `:cucumber-output-format` for configuring the output format

**Comment by nilswloka** [comment]
Not sure whether this is still needed now that lein cucumber takes command line options.

**Comment by rplevy-draker** [comment]
I think it is still good to be able to specify it in the project file, because in practice you want to be able to just type "lein cucumber" in the shell.

**Comment by rplevy-draker** [comment]
Oh, I misread, I thought you were talking about :cucumber-feature-path, sorry.  But my 2 cents would remain the same. :)

**Comment by yatesco** [comment]
Can I use a command line parameter to change the default report?  I also would like to produce a junit report (to help Jenkins a bit)

**Comment by mva** [comment]
I'm using calls like `lein cucumber --format pretty` to change the report format.  This works, because the command line options are passed on to cucumber.  Cucumber also knows the `--help` option if I remember correctly, but nowadays this is evaluated directly by lein-cucumber and unfortunately its output does not include cucumber's usage summary.

**Comment by yatesco** [comment]
Excellent - thanks.  If I use 'junit' as the format it complains that I
must specify 'junit:output'.  I have tried a couple of ways but both fail:

[code]
lein cucumber --format junit -Djunit:output=test.xml
cucumber.runtime.CucumberException: You must supply an output argument to
junit. Like so: junit:output
[/code]

and

[code]
lein cucumber --format junit junit:output=test.xml
cucumber.runtime.CucumberException: You must supply an output argument to
junit. Like so: junit:output
[/code]

Any ideas?

**Comment by mva** [comment]
Maybe `lein cucumber --format junit:test.xml`?

**Comment by yatesco** [comment]
Doh!  Thanks Michael.

**Comment by nilswloka** [comment]
I'm going to close this issue because, as @mva described, you can just configure the underlying Cucumber Runtime directly.
